name: cansig-env
channels:
  - defaults
dependencies:
  - pip:
    - anndata==0.8.0
    - attrs==22.2.0
    - cansig==0.2.2
    - flax==0.6.3
    - frozenlist==1.3.3
    - gseapy==1.0.3
    - h5py==3.7.0
    - idna==3.4
    - igraph==0.10.3
    - infercnvpy==0.4.0
    - jax==0.4.1
    - jaxlib==0.4.1
    - joblib==1.2.0
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - leidenalg==0.9.1
    - matplotlib==3.6.2
    - matplotlib-inline==0.1.6
    - natsort==8.2.0
    - networkx==3.0
    - numba==0.56.4
    - numpy==1.21.0
    - numpyro==0.10.1
    - optax==0.1.4
    - orbax==0.1.0
    - pandas==1.5.2
    - petname==2.6
    - pydantic==1.10.4
    - pyro-api==0.1.2
    - pyro-ppl==1.8.4
    - pytoml==0.1.21
    - pytorch-lightning==1.7.7
    - pyyaml==6.0
    - requests==2.28.1
    - scanpy==1.9.1
    - scikit-learn==1.2.0
    - scipy==1.10.0
    - scvi-tools==0.19.0
    - seaborn==0.12.2
    - statsmodels==0.13.5
    - tensorboard==2.11.0
    - torch==1.13.1
    - torchmetrics==0.11.0
    - umap-learn==0.5.3
    - urllib3==1.26.13
