# This pipeline checks whether the package
# installs properly, passes unit tests and whether
# the code formatting is right.
name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
      - name: Install the module
        run: pip install ".[test]"
      - name: Run unit tests
        run: pytest
      - name: Install dev dependencies
        run: pip install -r requirements-dev.txt
      - name: Run Flake8 check
        run: flake8
      - name: Run pytype check
        run: pytype cansig
