name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
      - name: Install the module
        run: pip install ".[test]"
      - name: Run unit tests
        run: pytest

