# Builds Sphinx documentation and pushes it to the gh-pages branch.
# This is based on https://github.com/marketplace/actions/sphinx-to-github-pages
name: Pages
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
    - uses: actions/checkout@main
      with:
        fetch-depth: 0
    - name: Build and Commit
      uses: sphinx-notes/pages@v2
    - name: Push changes
      uses: ad-m/github-push-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages

