# Based on
# https://dev.to/arnu515/create-a-pypi-pip-package-test-it-and-publish-it-using-github-actions-part-2-1o83
name: Test and upload to TestPyPI

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8 
      - name: "Installs and upgrades pip, installs other dependencies and installs the package from setup.py"
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools wheel twine
          pip install -r requirements.txt
          python3 setup.py install
      - name: Run unit tests
        run: pytest
      - name: Build and upload to TestPyPI
        run: |
          python3 setup.py sdist bdist_wheel
          python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}
          TWINE_REPOSITORY: testpypi

